// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBw8gFhOLo_LiKTVf6eqKNlkRsVhrKAdeY',
    appId: '1:311636756306:web:e96a929882ad258ed51c8b',
    messagingSenderId: '311636756306',
    projectId: 'fir-sys-47c75',
    authDomain: 'fir-sys-47c75.firebaseapp.com',
    storageBucket: 'fir-sys-47c75.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhRuqQGxzr8PLle74xBQqMbwQLmLUO71w',
    appId: '1:311636756306:android:9353705c65c695eed51c8b',
    messagingSenderId: '311636756306',
    projectId: 'fir-sys-47c75',
    storageBucket: 'fir-sys-47c75.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjh01K7UYreHlpBKnsqUnxThmPXU00tLo',
    appId: '1:311636756306:ios:c5c0fabd502e1808d51c8b',
    messagingSenderId: '311636756306',
    projectId: 'fir-sys-47c75',
    storageBucket: 'fir-sys-47c75.appspot.com',
    iosBundleId: 'com.example.deliveryControlWeb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDjh01K7UYreHlpBKnsqUnxThmPXU00tLo',
    appId: '1:311636756306:ios:9ca2f8fd1a771caad51c8b',
    messagingSenderId: '311636756306',
    projectId: 'fir-sys-47c75',
    storageBucket: 'fir-sys-47c75.appspot.com',
    iosBundleId: 'com.example.deliveryControlWeb.RunnerTests',
  );
}
